In [15]:
# Set environment paths
import pandas as pd
import numpy as np
import os

# Get the project root directory (two levels up from current directory)
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.getcwd()))
# Define data directory
DATA_DIR = os.path.join(PROJECT_ROOT, "app/data")

# Load CSV files into dataframes
tickets_df = pd.read_csv(os.path.join(DATA_DIR, "tickets.csv"))
ticket_details_df = pd.read_csv(os.path.join(DATA_DIR, "ticket_details.csv"))

print(f"Loaded {len(tickets_df)} tickets")
print(f"Loaded {len(ticket_details_df)} ticket details")

Loaded 30 tickets
Loaded 30 ticket details

In [3]:
tickets_df.head()

,cc_emails,fwd_emails,reply_cc_emails,ticket_cc_emails,ticket_bcc_emails,fr_escalated,spam,email_config_id,group_id,priority,...,id,type,due_by,fr_due_by,is_escalated,custom_fields,created_at,updated_at,associated_tickets_count,tags
0,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,8234,NaN,2025-02-23T21:10:52Z,2025-02-21T21:10:52Z,False,{'cf_subscriptions': None},2025-02-20T21:10:52Z,2025-02-20T21:11:57Z,NaN,[]
1,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,8233,NaN,2025-02-22T07:30:45Z,2025-02-20T07:30:45Z,False,{'cf_subscriptions': None},2025-02-19T07:30:45Z,2025-02-19T14:55:31Z,NaN,[]
2,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,8228,NaN,2025-02-21T06:58:04Z,2025-02-19T06:58:04Z,False,{'cf_subscriptions': None},2025-02-18T06:58:04Z,2025-02-18T20:32:54Z,NaN,[]
3,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,8227,NaN,2025-02-20T23:56:26Z,2025-02-18T23:56:26Z,False,{'cf_subscriptions': None},2025-02-17T23:56:26Z,2025-02-18T03:48:40Z,NaN,[]
4,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,8226,NaN,2025-02-22T10:18:17Z,2025-02-18T16:05:30Z,False,{'cf_subscriptions': None},2025-02-17T16:05:30Z,2025-02-19T14:57:12Z,NaN,[]

In [4]:
tickets_df.describe()

,email_config_id,group_id,priority,requester_id,responder_id,source,company_id,status,association_type,product_id,id,type,associated_tickets_count
count,2.500000e+01,0.0,30.0,3.000000e+01,3.000000e+01,30.000000,0.0,30.000000,0.0,0.0,30.000000,0.0,0.0
mean,5.000016e+09,NaN,1.0,1.205911e+10,8.765109e+09,1.166667,NaN,5.200000,NaN,NaN,8215.066667,NaN,NaN
std,0.000000e+00,NaN,0.0,4.141181e+06,3.561658e+09,0.379049,NaN,0.406838,NaN,NaN,9.864368,NaN,NaN
min,5.000016e+09,NaN,1.0,1.203893e+10,5.021538e+09,1.000000,NaN,5.000000,NaN,NaN,8199.000000,NaN,NaN
25%,5.000016e+09,NaN,1.0,1.206034e+10,5.021538e+09,1.000000,NaN,5.000000,NaN,NaN,8207.250000,NaN,NaN
50%,5.000016e+09,NaN,1.0,1.206042e+10,1.203734e+10,1.000000,NaN,5.000000,NaN,NaN,8214.500000,NaN,NaN
75%,5.000016e+09,NaN,1.0,1.206046e+10,1.203734e+10,1.000000,NaN,5.000000,NaN,NaN,8222.750000,NaN,NaN
max,5.000016e+09,NaN,1.0,1.206051e+10,1.205545e+10,2.000000,NaN,6.000000,NaN,NaN,8234.000000,NaN,NaN

In [5]:
ticket_details_df.head()

,cc_emails,fwd_emails,reply_cc_emails,ticket_cc_emails,ticket_bcc_emails,fr_escalated,spam,email_config_id,group_id,priority,...,fr_due_by,is_escalated,description,description_text,custom_fields,created_at,updated_at,tags,attachments,source_additional_info
0,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,2025-02-21T21:10:52Z,False,<div>You are currently on a Free Olark account...,You are currently on a Free Olark account. Get...,{'cf_subscriptions': None},2025-02-20T21:10:52Z,2025-02-20T21:11:57Z,[],[],NaN
1,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,2025-02-20T07:30:45Z,False,"<div dir=""ltr"">Hi Support Team, <br><br>I'm st...","Hi Support Team,\r\n\r\nI'm still struggling t...",{'cf_subscriptions': None},2025-02-19T07:30:45Z,2025-02-19T14:55:31Z,[],[],NaN
2,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,2025-02-19T06:58:04Z,False,"<div dir=""ltr"">Dear Support Team, <div><br></d...","Dear Support Team,\r\n\r\nI recently purchased...",{'cf_subscriptions': None},2025-02-18T06:58:04Z,2025-02-18T20:32:54Z,[],[],NaN
3,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,2025-02-18T23:56:26Z,False,<div>You are currently on a Free Olark account...,You are currently on a Free Olark account. Get...,{'cf_subscriptions': None},2025-02-17T23:56:26Z,2025-02-18T03:48:40Z,[],[],NaN
4,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,2025-02-18T16:05:30Z,False,"<div dir=""ltr"">\n<div>Hi Michael,<br><br>In or...","Hi Michael,\r\n\r\nIn order to work with a pay...",{'cf_subscriptions': None},2025-02-17T16:05:30Z,2025-02-19T14:57:12Z,[],[],NaN

In [6]:
ticket_details_df.describe()

,email_config_id,group_id,priority,requester_id,responder_id,source,company_id,status,association_type,product_id,id,type,source_additional_info
count,2.500000e+01,0.0,30.0,3.000000e+01,3.000000e+01,30.000000,0.0,30.000000,0.0,0.0,30.000000,0.0,0.0
mean,5.000016e+09,NaN,1.0,1.205911e+10,8.765109e+09,1.166667,NaN,5.200000,NaN,NaN,8215.066667,NaN,NaN
std,0.000000e+00,NaN,0.0,4.141181e+06,3.561658e+09,0.379049,NaN,0.406838,NaN,NaN,9.864368,NaN,NaN
min,5.000016e+09,NaN,1.0,1.203893e+10,5.021538e+09,1.000000,NaN,5.000000,NaN,NaN,8199.000000,NaN,NaN
25%,5.000016e+09,NaN,1.0,1.206034e+10,5.021538e+09,1.000000,NaN,5.000000,NaN,NaN,8207.250000,NaN,NaN
50%,5.000016e+09,NaN,1.0,1.206042e+10,1.203734e+10,1.000000,NaN,5.000000,NaN,NaN,8214.500000,NaN,NaN
75%,5.000016e+09,NaN,1.0,1.206046e+10,1.203734e+10,1.000000,NaN,5.000000,NaN,NaN,8222.750000,NaN,NaN
max,5.000016e+09,NaN,1.0,1.206051e+10,1.205545e+10,2.000000,NaN,6.000000,NaN,NaN,8234.000000,NaN,NaN

In [7]:
# Set the ID column as the index
ticket_details_df.set_index('id', inplace=True)
ticket_details_df.head()

,cc_emails,fwd_emails,reply_cc_emails,ticket_cc_emails,ticket_bcc_emails,fr_escalated,spam,email_config_id,group_id,priority,...,fr_due_by,is_escalated,description,description_text,custom_fields,created_at,updated_at,tags,attachments,source_additional_info
id,,,,,,,,,,,,,,,,,,,,,
8234,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,2025-02-21T21:10:52Z,False,<div>You are currently on a Free Olark account...,You are currently on a Free Olark account. Get...,{'cf_subscriptions': None},2025-02-20T21:10:52Z,2025-02-20T21:11:57Z,[],[],NaN
8233,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,2025-02-20T07:30:45Z,False,"<div dir=""ltr"">Hi Support Team, <br><br>I'm st...","Hi Support Team,\r\n\r\nI'm still struggling t...",{'cf_subscriptions': None},2025-02-19T07:30:45Z,2025-02-19T14:55:31Z,[],[],NaN
8228,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,2025-02-19T06:58:04Z,False,"<div dir=""ltr"">Dear Support Team, <div><br></d...","Dear Support Team,\r\n\r\nI recently purchased...",{'cf_subscriptions': None},2025-02-18T06:58:04Z,2025-02-18T20:32:54Z,[],[],NaN
8227,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,2025-02-18T23:56:26Z,False,<div>You are currently on a Free Olark account...,You are currently on a Free Olark account. Get...,{'cf_subscriptions': None},2025-02-17T23:56:26Z,2025-02-18T03:48:40Z,[],[],NaN
8226,[],[],[],[],[],False,False,5.000016e+09,NaN,1,...,2025-02-18T16:05:30Z,False,"<div dir=""ltr"">\n<div>Hi Michael,<br><br>In or...","Hi Michael,\r\n\r\nIn order to work with a pay...",{'cf_subscriptions': None},2025-02-17T16:05:30Z,2025-02-19T14:57:12Z,[],[],NaN

### Consistent Data Types & Missing Values

In [8]:
# Convert timestamps to datetime
for col in ['created_at', 'updated_at']:
    tickets_df[col] = pd.to_datetime(tickets_df[col])
    ticket_details_df[col] = pd.to_datetime(ticket_details_df[col])
# Calculate basic time-related features
ticket_details_df['response_time_hours'] = (ticket_details_df['updated_at'] - ticket_details_df['created_at']).dt.total_seconds() / 3600
ticket_details_df['created_date'] = ticket_details_df['created_at'].dt.date
ticket_details_df['created_hour'] = ticket_details_df['created_at'].dt.hour
ticket_details_df['created_day_of_week'] = ticket_details_df['created_at'].dt.day_name()

print("\n=== Ticket Details DataFrame Data Types ===")
print(ticket_details_df.dtypes)

print("\n=== Missing Values in Ticket Details DataFrame ===")
print(ticket_details_df.isnull().sum())

=== Ticket Details DataFrame Data Types ===
cc_emails                              object
fwd_emails                             object
reply_cc_emails                        object
ticket_cc_emails                       object
ticket_bcc_emails                      object
fr_escalated                             bool
spam                                     bool
email_config_id                       float64
group_id                              float64
priority                                int64
requester_id                            int64
responder_id                            int64
source                                  int64
company_id                            float64
status                                  int64
subject                                object
association_type                      float64
support_email                          object
to_emails                              object
product_id                            float64
type                                  float64
due_by                                 object
fr_due_by                              object
is_escalated                             bool
description                            object
description_text                       object
custom_fields                          object
created_at                datetime64[ns, UTC]
updated_at                datetime64[ns, UTC]
tags                                   object
attachments                            object
source_additional_info                float64
response_time_hours                   float64
created_date                           object
created_hour                            int32
created_day_of_week                    object
dtype: object

=== Missing Values in Ticket Details DataFrame ===
cc_emails                  0
fwd_emails                 0
reply_cc_emails            0
ticket_cc_emails           0
ticket_bcc_emails          0
fr_escalated               0
spam                       0
email_config_id            5
group_id                  30
priority                   0
requester_id               0
responder_id               0
source                     0
company_id                30
status                     0
subject                    0
association_type          30
support_email              5
to_emails                  5
product_id                30
type                      30
due_by                     0
fr_due_by                  0
is_escalated               0
description                0
description_text           0
custom_fields              0
created_at                 0
updated_at                 0
tags                       0
attachments                0
source_additional_info    30
response_time_hours        0
created_date               0
created_hour               0
created_day_of_week        0
dtype: int64

In [9]:
# First, let's look at the unique values in each column
print("=== Column Value Counts ===")
for column in ticket_details_df.columns:
    n_unique = ticket_details_df[column].nunique()
    print(f"\n{column}: {n_unique} unique values")
    
    # For columns with reasonable number of unique values, show distribution
    if n_unique < 10 and n_unique > 0:
        print(ticket_details_df[column].value_counts())

# Check for any duplicate entries
print("\n=== Duplicate Check ===")
print(f"Number of duplicate rows: {ticket_details_df.duplicated().sum()}")

=== Column Value Counts ===

cc_emails: 5 unique values
cc_emails
[]                                                      26
['israel.farfan@provi.com', 'devops@provi.com']          1
['devops@provi.com']                                     1
['michael@quotaguard.com', 'randall@quotaguard.com']     1
['accountspayable@eidebailly.com']                       1
Name: count, dtype: int64

fwd_emails: 1 unique values
fwd_emails
[]    30
Name: count, dtype: int64

reply_cc_emails: 5 unique values
reply_cc_emails
[]                                                      26
['israel.farfan@provi.com', 'devops@provi.com']          1
['devops@provi.com']                                     1
['michael@quotaguard.com', 'randall@quotaguard.com']     1
['accountspayable@eidebailly.com']                       1
Name: count, dtype: int64

ticket_cc_emails: 3 unique values
ticket_cc_emails
[]                                                 28
['israel.farfan@provi.com', 'devops@provi.com']     1
['devops@provi.com']                                1
Name: count, dtype: int64

ticket_bcc_emails: 1 unique values
ticket_bcc_emails
[]    30
Name: count, dtype: int64

fr_escalated: 2 unique values
fr_escalated
False    28
True      2
Name: count, dtype: int64

spam: 1 unique values
spam
False    30
Name: count, dtype: int64

email_config_id: 1 unique values
email_config_id
5.000016e+09    25
Name: count, dtype: int64

group_id: 0 unique values

priority: 1 unique values
priority
1    30
Name: count, dtype: int64

requester_id: 28 unique values

responder_id: 3 unique values
responder_id
5021537993     14
12037336667    13
12055451471     3
Name: count, dtype: int64

source: 2 unique values
source
1    25
2     5
Name: count, dtype: int64

company_id: 0 unique values

status: 2 unique values
status
5    24
6     6
Name: count, dtype: int64

subject: 26 unique values

association_type: 0 unique values

support_email: 1 unique values
support_email
quotaguardcomsupport@quotaguard.freshdesk.com    25
Name: count, dtype: int64

to_emails: 5 unique values
to_emails
['support@quotaguard.com']                                                        19
['"Michael Crown" <support@quotaguard.com>']                                       3
['"support@quotaguard.com" <support@quotaguard.com>']                              1
['michael@quotaguard.com', 'support@quotaguard.com', 'randall@quotaguard.com']     1
['support@quotaguard.com', 'accountspayable@eidebailly.com']                       1
Name: count, dtype: int64

product_id: 0 unique values

type: 0 unique values

due_by: 30 unique values

fr_due_by: 30 unique values

is_escalated: 2 unique values
is_escalated
False    29
True      1
Name: count, dtype: int64

description: 30 unique values

description_text: 30 unique values

custom_fields: 1 unique values
custom_fields
{'cf_subscriptions': None}    30
Name: count, dtype: int64

created_at: 30 unique values

updated_at: 29 unique values

tags: 1 unique values
tags
[]    30
Name: count, dtype: int64

attachments: 2 unique values
attachments
[]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           29
[{'id': 12156573264, 'content_type': 'application/octet-stream', 'size': 95905, 'name': "Remittance Advice for QUOTAGUARD STATIC IP'S.pdf", 'attachment_url': 'https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/12156573264/original/Remittance%20Advice%20for%20QUOTAGUARD%20STATIC%20IP%27S.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAS6FNSMY2XLZULJPI%2F20250221%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250221T062555Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=dfb119e0a041b58e72491c523dbe8929327db62438181dd429ea6861e66566d4', 'created_at': '2025-02-06T16:59:26Z', 'updated_at': '2025-02-06T16:59:26Z'}]     1
Name: count, dtype: int64

source_additional_info: 0 unique values

response_time_hours: 30 unique values

created_date: 13 unique values

created_hour: 16 unique values

created_day_of_week: 7 unique values
created_day_of_week
Thursday     7
Wednesday    6
Friday       6
Monday       4
Saturday     3
Tuesday      2
Sunday       2
Name: count, dtype: int64

=== Duplicate Check ===
Number of duplicate rows: 0

In [10]:
# Basic statistics for numeric columns
numeric_columns = ticket_details_df.select_dtypes(include=['int64', 'float64']).columns
print("\n=== Numeric Column Statistics ===")
print(ticket_details_df[numeric_columns].describe())

# Check for any potential data quality issues
print("\n=== Data Quality Checks ===")
# Check for any negative values in numeric columns
for col in numeric_columns:
    neg_count = (ticket_details_df[col] < 0).sum()
    if neg_count > 0:
        print(f"Found {neg_count} negative values in {col}")

=== Numeric Column Statistics ===
       email_config_id  group_id  priority  requester_id  responder_id  \
count     2.500000e+01       0.0      30.0  3.000000e+01  3.000000e+01
mean      5.000016e+09       NaN       1.0  1.205911e+10  8.765109e+09
std       0.000000e+00       NaN       0.0  4.141181e+06  3.561658e+09
min       5.000016e+09       NaN       1.0  1.203893e+10  5.021538e+09
25%       5.000016e+09       NaN       1.0  1.206034e+10  5.021538e+09
50%       5.000016e+09       NaN       1.0  1.206042e+10  1.203734e+10
75%       5.000016e+09       NaN       1.0  1.206046e+10  1.203734e+10
max       5.000016e+09       NaN       1.0  1.206051e+10  1.205545e+10

          source  company_id     status  association_type  product_id  type  \
count  30.000000         0.0  30.000000               0.0         0.0   0.0
mean    1.166667         NaN   5.200000               NaN         NaN   NaN
std     0.379049         NaN   0.406838               NaN         NaN   NaN
min     1.000000         NaN   5.000000               NaN         NaN   NaN
25%     1.000000         NaN   5.000000               NaN         NaN   NaN
50%     1.000000         NaN   5.000000               NaN         NaN   NaN
75%     1.000000         NaN   5.000000               NaN         NaN   NaN
max     2.000000         NaN   6.000000               NaN         NaN   NaN

       source_additional_info  response_time_hours
count                     0.0            30.000000
mean                      NaN            31.826194
std                       NaN            54.877741
min                       NaN             0.000556
25%                       NaN             0.463611
50%                       NaN            14.339444
75%                       NaN            29.147569
max                       NaN           238.478611

=== Data Quality Checks ===

In [19]:
# Get list of numeric columns for analysis
string_id_cols = [
    'email_config_id',
    'requester_id',
    'responder_id',
    'product_id',
    'company_id',
    'group_id',
    'email_config_id'
]

# Convert int64 columns to string
# First, let's identify which columns are int64
int_columns = ticket_details_df[string_id_cols].columns
print("Columns being converted from int64 to string:", int_columns.tolist())

# Convert those columns to string
for col in int_columns:
    ticket_details_df[col] = ticket_details_df[col].astype(str)

# Verify the conversion
print("\nNew data types after conversion:")
print(ticket_details_df[int_columns].dtypes)

print("\n Let's check the unique data types in the columns")
print(ticket_details_df[int_columns].describe())

Columns being converted from int64 to string: ['email_config_id', 'requester_id', 'responder_id', 'product_id', 'company_id', 'group_id', 'email_config_id']

New data types after conversion:
email_config_id    object
requester_id       object
responder_id       object
product_id         object
company_id         object
group_id           object
email_config_id    object
dtype: object

 Let's check the unique data types in the columns
       email_config_id requester_id responder_id product_id company_id  \
count               30           30           30         30         30
unique               2           28            3          1          1
top       5000016478.0  12060445891   5021537993        nan        nan
freq                25            2           14         30         30

       group_id email_config_id
count        30              30
unique        1               2
top         nan    5000016478.0
freq         30              25

In [25]:
# Check for future dates in timestamp columns
current_date = pd.Timestamp.now(tz='UTC')
for col in ['created_at', 'updated_at']:
    # Convert column to UTC if it isn't already
    if ticket_details_df[col].dt.tz is None:
        ticket_details_df[col] = ticket_details_df[col].dt.tz_localize('UTC')
    future_dates = ticket_details_df[col].dt.tz_localize(None) > current_date.tz_localize(None)
    if future_dates.sum() > 0:
        print(f"Found {future_dates.sum()} future dates in {col}")

### Statistical Analysis of Numerical Columns

### Categorical Values

In [30]:
# Create mappings for priority and status
priority_map = {
    1: 'Low',
    2: 'Medium',
    3: 'High',
    4: 'Urgent'
}

status_map = {
    2: 'Open',
    3: 'Pending',
    4: 'Resolved',
    5: 'Closed',
    6: 'Waiting on Customer',
    7: 'Waiting on Third Party'
}

# Create mapping for source
source_map = {
    1: 'Email',
    2: 'Portal',
    3: 'Phone',
    7: 'Chat',
    9: 'Feedback Widget',
    10: 'Outbound Email'
}

# Convert priority to categorical with ordered levels
ticket_details_df['priority_category'] = (ticket_details_df['priority']
                                        .map(priority_map)
                                        .astype('category'))

# Set the priority category order
ticket_details_df['priority_category'] = (ticket_details_df['priority_category']
                                        .cat.set_categories(['Low', 'Medium', 'High', 'Urgent'], 
                                                          ordered=True))

# Convert status to categorical
ticket_details_df['status_category'] = (ticket_details_df['status']
                                      .map(status_map)
                                      .astype('category'))

# Convert source to categorical
ticket_details_df['source_category'] = (ticket_details_df['source']
                                      .map(source_map)
                                      .astype('category'))


# Verify the conversions
print("=== Priority Categories ===")
print(ticket_details_df['priority_category'].value_counts().sort_index())
print("\n=== Status Categories ===")
print(ticket_details_df['status_category'].value_counts())
print("=== Source Categories ===")
print(ticket_details_df['source_category'].value_counts())


# Check for any unmapped values
print("\n=== Checking for Unmapped Values ===")
print("Priority unmapped:", ticket_details_df[ticket_details_df['priority_category'].isna()]['priority'].unique())
print("Status unmapped:", ticket_details_df[ticket_details_df['status_category'].isna()]['status'].unique())
unmapped_sources = ticket_details_df[ticket_details_df['source_category'].isna()]['source'].unique()
print("Source unmapped:", unmapped_sources if len(unmapped_sources) > 0 else "None")

=== Priority Categories ===
priority_category
Low       30
Medium     0
High       0
Urgent     0
Name: count, dtype: int64

=== Status Categories ===
status_category
Closed                 24
Waiting on Customer     6
Name: count, dtype: int64
=== Source Categories ===
source_category
Email     25
Portal     5
Name: count, dtype: int64

=== Checking for Unmapped Values ===
Priority unmapped: []
Status unmapped: []
Source unmapped: None

### Boolean Values

In [32]:
# Identify boolean columns
bool_columns = [
    'spam',
    'fr_escalated',
    'is_escalated',
]

# Basic analysis of boolean features
print("=== Boolean Features Analysis ===")
for col in bool_columns:
    value_counts = ticket_details_df[col].value_counts()
    percentages = ticket_details_df[col].value_counts(normalize=True) * 100
    
    print(f"\n{col.replace('_', ' ').title()}:")
    print(f"True count: {value_counts.get(True, 0)} ({percentages.get(True, 0):.2f}%)")
    print(f"False count: {value_counts.get(False, 0)} ({percentages.get(False, 0):.2f}%)")
    print(f"Missing values: {ticket_details_df[col].isna().sum()}")

# Cross-tabulation with priority categories
print("\n=== Boolean Features by Priority ===")
for col in bool_columns:
    print(f"\n{col.replace('_', ' ').title()} by Priority:")
    print(pd.crosstab(ticket_details_df[col], 
                      ticket_details_df['priority_category'], 
                      normalize='columns') * 100)

# Cross-tabulation with status categories
print("\n=== Boolean Features by Status ===")
for col in bool_columns:
    print(f"\n{col.replace('_', ' ').title()} by Status:")
    print(pd.crosstab(ticket_details_df[col], 
                      ticket_details_df['status_category'], 
                      normalize='columns') * 100)

# Check for correlations between boolean features
print("\n=== Correlations Between Boolean Features ===")
bool_correlations = ticket_details_df[bool_columns].corr()
print(bool_correlations)

# Find significant correlations (|correlation| > 0.3)
print("\n=== Significant Boolean Correlations (|correlation| > 0.3) ===")
for col1 in bool_columns:
    for col2 in bool_columns:
        if col1 < col2:  # avoid printing both (a,b) and (b,a)
            corr = bool_correlations.loc[col1, col2]
            if abs(corr) > 0.3:
                print(f"{col1} vs {col2}: {corr:.3f}")

=== Boolean Features Analysis ===

Spam:
True count: 0 (0.00%)
False count: 30 (100.00%)
Missing values: 0

Fr Escalated:
True count: 2 (6.67%)
False count: 28 (93.33%)
Missing values: 0

Is Escalated:
True count: 1 (3.33%)
False count: 29 (96.67%)
Missing values: 0

=== Boolean Features by Priority ===

Spam by Priority:
priority_category    Low
spam
False              100.0

Fr Escalated by Priority:
priority_category        Low
fr_escalated
False              93.333333
True                6.666667

Is Escalated by Priority:
priority_category        Low
is_escalated
False              96.666667
True                3.333333

=== Boolean Features by Status ===

Spam by Status:
status_category  Closed  Waiting on Customer
spam
False             100.0                100.0

Fr Escalated by Status:
status_category     Closed  Waiting on Customer
fr_escalated
False            91.666667                100.0
True              8.333333                  0.0

Is Escalated by Status:
status_category     Closed  Waiting on Customer
is_escalated
False            95.833333                100.0
True              4.166667                  0.0

=== Correlations Between Boolean Features ===
              spam  fr_escalated  is_escalated
spam           NaN           NaN           NaN
fr_escalated   NaN      1.000000     -0.049629
is_escalated   NaN     -0.049629      1.000000

=== Significant Boolean Correlations (|correlation| > 0.3) ===

### Time to Close Analysis

In [36]:
# Calculate time to close in hours
ticket_details_df['time_to_close_hours'] = (ticket_details_df['updated_at'] - ticket_details_df['created_at']).dt.total_seconds() / 3600

# Create a new column for time to close in days
ticket_details_df['time_to_close_days'] = (ticket_details_df['updated_at'] - ticket_details_df['created_at']).dt.days

print(ticket_details_df['time_to_close_hours'].describe())
print(ticket_details_df['time_to_close_days'].describe())

count     30.000000
mean      31.826194
std       54.877741
min        0.000556
25%        0.463611
50%       14.339444
75%       29.147569
max      238.478611
Name: time_to_close_hours, dtype: float64
count    30.000000
mean      0.933333
std       2.196130
min       0.000000
25%       0.000000
50%       0.000000
75%       0.750000
max       9.000000
Name: time_to_close_days, dtype: float64

In [39]:
# Calculate time to close/resolve tickets
ticket_details_df['time_to_close'] = (ticket_details_df['updated_at'] - ticket_details_df['created_at']).dt.total_seconds() / 3600  # in hours

# Basic statistics for time to close
print("=== Time to Close Statistics (in hours) ===")
print(ticket_details_df['time_to_close'].describe())

# Calculate business metrics
print("\n=== Business Time Metrics ===")
print(f"Average time to close: {ticket_details_df['time_to_close'].mean():.2f} hours")
print(f"Median time to close: {ticket_details_df['time_to_close'].median():.2f} hours")
print(f"90th percentile: {ticket_details_df['time_to_close'].quantile(0.9):.2f} hours")
print(f"95th percentile: {ticket_details_df['time_to_close'].quantile(0.95):.2f} hours")

# Time to close by priority
print("\n=== Time to Close by Priority ===")
priority_stats = ticket_details_df.groupby('priority_category')['time_to_close'].agg([
    'count',
    'mean',
    'median',
    'std'
]).round(2)
print(priority_stats)

# Time to close by source
print("\n=== Time to Close by Source ===")
source_stats = ticket_details_df.groupby('source_category')['time_to_close'].agg([
    'count',
    'mean',
    'median',
    'std'
]).round(2)
print(source_stats)


# Calculate time bands for tickets
ticket_details_df['time_band'] = pd.cut(
    ticket_details_df['time_to_close'],
    bins=[0, 1, 4, 24, 72, float('inf')],
    labels=['< 1 hour', '1-4 hours', '4-24 hours', '1-3 days', '> 3 days']
)

print("\n=== Distribution of Time Bands ===")
time_band_dist = ticket_details_df['time_band'].value_counts().sort_index()
print(time_band_dist)

# Correlation with numeric features
numeric_cols = ['requester_id', 'responder_id', 'group_id', 'priority']
print("\n=== Correlation with Numeric Features ===")
correlations = ticket_details_df[numeric_cols + ['time_to_close']].corr()['time_to_close']
print(correlations)

# Analysis by boolean features
print("\n=== Average Time to Close by Boolean Features ===")
bool_cols = ['spam', 'fr_escalated', 'is_escalated']
for col in bool_cols:
    avg_time = ticket_details_df.groupby(col)['time_to_close'].mean()
    print(f"\n{col}:")
    print(avg_time)

# Time of day analysis
ticket_details_df['created_hour'] = ticket_details_df['created_at'].dt.hour
print("\n=== Average Time to Close by Hour of Day Ticket Created===")
hour_stats = ticket_details_df.groupby('created_hour')['time_to_close'].agg([
    'count',
    'mean',
    'median'
]).round(2)
print(hour_stats)

# Day of week analysis
ticket_details_df['created_day'] = ticket_details_df['created_at'].dt.day_name()
print("\n=== Average Time to Close by Day of Week Ticket Created===")
day_stats = ticket_details_df.groupby('created_day')['time_to_close'].agg([
    'count',
    'mean',
    'median'
]).round(2)
print(day_stats)

=== Time to Close Statistics (in hours) ===
count     30.000000
mean      31.826194
std       54.877741
min        0.000556
25%        0.463611
50%       14.339444
75%       29.147569
max      238.478611
Name: time_to_close, dtype: float64

=== Business Time Metrics ===
Average time to close: 31.83 hours
Median time to close: 14.34 hours
90th percentile: 76.52 hours
95th percentile: 149.74 hours

=== Time to Close by Priority ===
                   count   mean  median    std
priority_category
Low                   30  31.83   14.34  54.88
Medium                 0    NaN     NaN    NaN
High                   0    NaN     NaN    NaN
Urgent                 0    NaN     NaN    NaN

=== Time to Close by Source ===
                 count   mean  median    std
source_category
Email               25  38.18   18.41  58.20
Portal               5   0.06    0.06   0.02

=== Distribution of Time Bands ===
time_band
< 1 hour       8
1-4 hours      3
4-24 hours    11
1-3 days       5
> 3 days       3
Name: count, dtype: int64

=== Correlation with Numeric Features ===
requester_id     0.155419
responder_id     0.089168
group_id              NaN
priority              NaN
time_to_close    1.000000
Name: time_to_close, dtype: float64

=== Average Time to Close by Boolean Features ===

spam:
spam
False    31.826194
Name: time_to_close, dtype: float64

fr_escalated:
fr_escalated
False    30.672996
True     47.970972
Name: time_to_close, dtype: float64

is_escalated:
is_escalated
False     27.085623
True     169.302778
Name: time_to_close, dtype: float64

=== Average Time to Close by Hour of Day Ticket Created===
              count    mean  median
created_hour
0                 3   11.38   15.10
2                 1   16.27   16.27
3                 1    0.01    0.01
6                 3   57.47   32.99
7                 1    7.41    7.41
8                 4   12.42    9.24
10                1    5.55    5.55
13                1    2.21    2.21
14                1  238.48  238.48
15                1  169.30  169.30
16                3   39.30   46.86
17                2   16.05   16.05
19                2    9.89    9.89
21                3    0.57    0.07
22                1   64.77   64.77
23                2   11.52   11.52

=== Average Time to Close by Day of Week Ticket Created===
             count   mean  median
created_day
Friday           6  55.52   14.09
Monday           4  14.62    4.71
Saturday         3  11.75   16.27
Sunday           2  25.45   25.45
Thursday         7   6.90    0.06
Tuesday          2  16.00   16.00
Wednesday        6  66.12   47.07

/var/folders/nd/z10gkxp14_vbcbgjmpzd69200000gn/T/ipykernel_89763/3201008526.py:17: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  priority_stats = ticket_details_df.groupby('priority_category')['time_to_close'].agg([
/var/folders/nd/z10gkxp14_vbcbgjmpzd69200000gn/T/ipykernel_89763/3201008526.py:27: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  source_stats = ticket_details_df.groupby('source_category')['time_to_close'].agg([

### Visualizations

In [41]:
# Install required packages
!pip install seaborn matplotlib

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.9/294.9 kB 4.1 MB/s eta 0:00:00a 0:00:01
Collecting matplotlib
  Using cached matplotlib-3.10.0-cp311-cp311-macosx_10_12_x86_64.whl (8.2 MB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in /Users/millionairemacmillionairemac/Developer/Squirtle-Freshdesk-Chat-Agent/venv/lib/python3.11/site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in /Users/millionairemacmillionairemac/Developer/Squirtle-Freshdesk-Chat-Agent/venv/lib/python3.11/site-packages (from seaborn) (2.2.3)
Collecting contourpy>=1.0.1 (from matplotlib)
  Using cached contourpy-1.3.1-cp311-cp311-macosx_10_9_x86_64.whl (269 kB)
Collecting cycler>=0.10 (from matplotlib)
  Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting fonttools>=4.22.0 (from matplotlib)
  Using cached fonttools-4.56.0-cp311-cp311-macosx_10_9_x86_64.whl (2.3 MB)
Collecting kiwisolver>=1.3.1 (from matplotlib)
  Using cached kiwisolver-1.4.8-cp311-cp311-macosx_10_9_x86_64.whl (66 kB)
Requirement already satisfied: packaging>=20.0 in /Users/millionairemacmillionairemac/Developer/Squirtle-Freshdesk-Chat-Agent/venv/lib/python3.11/site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in /Users/millionairemacmillionairemac/Developer/Squirtle-Freshdesk-Chat-Agent/venv/lib/python3.11/site-packages (from matplotlib) (11.1.0)
Collecting pyparsing>=2.3.1 (from matplotlib)
  Using cached pyparsing-3.2.1-py3-none-any.whl (107 kB)
Requirement already satisfied: python-dateutil>=2.7 in /Users/millionairemacmillionairemac/Developer/Squirtle-Freshdesk-Chat-Agent/venv/lib/python3.11/site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/millionairemacmillionairemac/Developer/Squirtle-Freshdesk-Chat-Agent/venv/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/millionairemacmillionairemac/Developer/Squirtle-Freshdesk-Chat-Agent/venv/lib/python3.11/site-packages (from pandas>=1.2->seaborn) (2025.1)
Requirement already satisfied: six>=1.5 in /Users/millionairemacmillionairemac/Developer/Squirtle-Freshdesk-Chat-Agent/venv/lib/python3.11/site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)
Installing collected packages: pyparsing, kiwisolver, fonttools, cycler, contourpy, matplotlib, seaborn
Successfully installed contourpy-1.3.1 cycler-0.12.1 fonttools-4.56.0 kiwisolver-1.4.8 matplotlib-3.10.0 pyparsing-3.2.1 seaborn-0.13.2

[notice] A new release of pip is available: 23.1.2 -> 25.0.1
[notice] To update, run: pip install --upgrade pip

In [42]:
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Set the style for all plots
plt.style.use('seaborn')
sns.set_palette("husl")

# 1. Time to Close Distribution
fig, axes = plt.subplots(2, 1, figsize=(15, 12))

# Histogram with log scale
sns.histplot(data=ticket_details_df, x='time_to_close', bins=50, ax=axes[0])
axes[0].set_title('Distribution of Time to Close')
axes[0].set_xlabel('Hours')
axes[0].set_ylabel('Count')

# Same histogram with log scale
sns.histplot(data=ticket_details_df, x='time_to_close', bins=50, ax=axes[1])
axes[1].set_yscale('log')
axes[1].set_title('Distribution of Time to Close (Log Scale)')
axes[1].set_xlabel('Hours')
axes[1].set_ylabel('Count (Log)')

plt.tight_layout()
plt.show()

# 2. Time to Close by Priority and Status
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 8))

# Box plot for Priority
sns.boxplot(data=ticket_details_df, x='priority_category', y='time_to_close', ax=ax1)
ax1.set_title('Time to Close by Priority')
ax1.set_ylabel('Hours')
ax1.set_yscale('log')

# Box plot for Status
sns.boxplot(data=ticket_details_df, x='status_category', y='time_to_close', ax=ax2)
ax2.set_title('Time to Close by Status')
ax2.set_ylabel('Hours')
ax2.set_yscale('log')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# 3. Time Patterns
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(20, 8))

# Hour of Day Analysis
hourly_avg = ticket_details_df.groupby('created_hour')['time_to_close'].mean()
sns.lineplot(data=hourly_avg, ax=ax1)
ax1.set_title('Average Time to Close by Hour of Day')
ax1.set_xlabel('Hour of Day')
ax1.set_ylabel('Average Hours to Close')

# Day of Week Analysis
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
daily_avg = ticket_details_df.groupby('created_day')['time_to_close'].mean()
daily_avg = daily_avg.reindex(day_order)
sns.barplot(x=daily_avg.index, y=daily_avg.values, ax=ax2)
ax2.set_title('Average Time to Close by Day of Week')
ax2.set_xlabel('Day of Week')
ax2.set_ylabel('Average Hours to Close')
plt.xticks(rotation=45)

plt.tight_layout()
plt.show()

# 4. Source Analysis
plt.figure(figsize=(12, 6))
sns.boxplot(data=ticket_details_df, x='source_category', y='time_to_close')
plt.title('Time to Close by Source')
plt.yscale('log')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 5. Boolean Features Impact
fig, axes = plt.subplots(2, 3, figsize=(20, 12))
axes = axes.ravel()

bool_cols = ['spam', 'fr_escalated', 'is_escalated', 'source_from_email', 'deleted']
for idx, col in enumerate(bool_cols):
    sns.boxplot(data=ticket_details_df, x=col, y='time_to_close', ax=axes[idx])
    axes[idx].set_title(f'Time to Close by {col.replace("_", " ").title()}')
    axes[idx].set_yscale('log')
    axes[idx].set_ylabel('Hours')

plt.tight_layout()
plt.show()

# 6. Time Bands Distribution
plt.figure(figsize=(12, 6))
sns.countplot(data=ticket_details_df, x='time_band', order=['< 1 hour', '1-4 hours', '4-24 hours', '1-3 days', '> 3 days'])
plt.title('Distribution of Tickets by Time to Close Bands')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# 7. Correlation Heatmap
numeric_cols = ['requester_id', 'responder_id', 'group_id', 'priority', 'time_to_close']
plt.figure(figsize=(10, 8))
sns.heatmap(ticket_details_df[numeric_cols].corr(), 
            annot=True, 
            cmap='coolwarm', 
            center=0)
plt.title('Correlation Heatmap')
plt.tight_layout()
plt.show()

OSError: 'seaborn' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)